apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048-deploy
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: container
          image: REPLACE  
          ports:
            - containerPort: 3000  



